// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VesselTrackingSystem.Models
{
    public partial class Vessels
    {
        public Vessels()
        {
            VesselLocations = new HashSet<VesselLocations>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Imo { get; set; }
        public string Mmsi { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ICollection<VesselLocations> VesselLocations { get; set; }
    }
}